spring:
  application:
    name: pizzza-management-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/${REALM_NAME}
          authorities-claim-name: roles
          authority-prefix: ROLE_

  graphql:
    graphiql:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: ${SWAGGER_CLIENT_ID:swagger}
      use-pkce-with-authorization-code-grant: true
      additional-query-string-params:
        prompt: login
  api-docs:
    path: /v3/api-docs
